GRPC localhost:50051/bitcoinpayserver.v1.services.wallet.WalletService/Create
Content-Type: application/json

{
  "owner_x_pubkey": "tpubDG5KEfa5LG3NC7RLsJxxajR9MF7vZqKd1YexvS4LpVthKeu9gnGoNpt8FnUtb4iHnb4GbLD37LFHyCq4ouydRAesPhe1sZg4cqdiFSRvr92"
}